spring:
  profiles:
    active: development
    
authserver:
    hostname: localhost
    port: 8443
    contextPath: userauth
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:8889/account_service
    username: root
    password: root
    dbcp:
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8443/uaa/me
    client:
      accessTokenUri: http://localhost:8443/uaa/oauth/token
      userAuthorizationUri: http://localhost:8443/uaa/oauth/authorize
      clientId: iOSApp
      clientSecret: EZDoesItAll

eureka:
  instance:
    prefer-ip-address: true
    securePortEnabled: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/