spring:
  profiles:
    active: development
---
spring:
  profiles: development
eureka:
  instance:
    prefer-ip-address: true
    securePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/