spring:
  profiles:
    active: development
---
server:
  contextPath: /uaa
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:8889/user_auth_service?useSSL=false
    username: root
    password: root
    dbcp:
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
security:
  ignored: /resources/**
eureka:
  instance:
    prefer-ip-address: true
    securePortEnabled: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      